linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=lasote/conangcc49
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=lasote/conangcc49
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conangcc5
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conangcc6
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conangcc7
      #  - a x86 build for GCC
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conangcc7-i386
      # Clang compilation
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang39
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang39
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang50
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang50
      #  - a x86 build for Clang
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=1 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang50-i386
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_TOTAL_PAGES=2 CONAN_CURRENT_PAGE=2 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_DOCKER_IMAGE=lasote/conanclang50-i386
      # Apple jobs
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
