build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_BUILD_TYPES: Release
          CONAN_TOTAL_PAGES: 2
          CONAN_CURRENT_PAGE: 1
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
          CONAN_BUILD_TYPES: Release
          CONAN_TOTAL_PAGES: 2
          CONAN_CURRENT_PAGE: 2
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
          CONAN_VISUAL_VERSIONS: 11
          CONAN_BUILD_TYPES: Release
          CONAN_TOTAL_PAGES: 2
          CONAN_CURRENT_PAGE: 1
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          CONAN_TOTAL_PAGES: 2
          CONAN_CURRENT_PAGE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_sword_and_sorcery
  - conan user # It creates the conan data directory

test_script:
  - run_ci conanfile.py
